all: exo1 exo2 exo3 exo4

exo1:
	g++ -Wall -Wextra --std=c++23 exo1.cpp -o exo1

exo2:
	g++ -Wall -Wextra --std=c++23 exo2.cpp -o exo2

exo3:
	g++ -Wall -Wextra --std=c++23 exo3.cpp -o exo3

exo4:
	g++ -Wall -Wextra --std=c++23 exo4.cpp -o exo4

clean:
	rm exo1 exo2 exo3 exo4