all: exo1 exo2 exo3

exo1:
	g++ -Wall -Wextra -std=c++23 exo1.cpp -o exo1

exo2:
	g++ -Wall -Wextra -std=c++23 exo2.cpp -o exo2

exo3:
	g++ -Wall -Wextra -std=c++23 exo3.cpp -o exo3

clean:
	rm -f exo1 exo2 exo3